# Python environment


```{r, decorate=TRUE}
library(reticulate)
```

```{r, decorate=TRUE}
# get the current folder of the notebook to set the relative path
getwd()
```

```{r, decorate=TRUE}
library(reticulate)
use_condaenv("r-python", required = TRUE)
py_config()
```

```{r, eval=FALSE, echo=FALSE, decorate=TRUE}
reticulate::use_python("..\\..\\python-3.6.7.amd64\\python.exe")
reticulate::py_config()
reticulate::py_available()
```

```{python, decorate=TRUE}
# this chunk with matplotlib will only run if the PyQt plugin path has been specified
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
```

```{python, decorate=TRUE}
t = np.arange(0.0, 2.0, 0.01)
s = 1 + np.sin(2 * np.pi * t)

fig, ax = plt.subplots()
ax.plot(t, s)

ax.set(xlabel='time (s)', ylabel='voltage (mV)',
       title='About as simple as it gets, folks')
ax.grid()

plt.show()
```


```{r eval=FALSE, decorate=TRUE}
# load the package that makes R and Python talk
library(reticulate)

# set the preferred Python to execute
user_profile <- Sys.getenv("USERPROFILE")                    # user folder
python_portable <- normalizePath(file.path(user_profile,     # Python location
                                "WPy-3710zero/python-3.7.1.amd64/python.exe"))
reticulate::use_python(python_portable, required = TRUE)
reticulate::py_config()
```

```{r, decorate=TRUE}
# library(reticulate)
# reticulate::use_python("..\\..\\python-3.6.7.amd64\\python.exe")
# reticulate::py_config()
# reticulate::py_available()
```

```{r, eval=FALSE, decorate=TRUE}
# load the package that makes R and Python talk
library(reticulate)

# set the preferred Python to execute
user_profile <- Sys.getenv("USERPROFILE")                    # user folder
python_portable <- normalizePath(file.path(user_profile,     # Python location
                                "WPy-3710zero/python-3.7.1.amd64/python.exe"))

reticulate::use_python(python_portable, required = TRUE)
 
# find out if it took it
reticulate::py_config()
```
